name: "Deploy"

on:
  push:
    branches:
      - "main"
      - "*.*.*"
      - "develop"

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  stop:
    runs-on: ubuntu-latest

    steps:
      - name: Stop
        run: sleep 180

  drop_db:
    runs-on: ubuntu-latest

    needs: stop

    steps:
      - name: Checkout repository
        run: sleep 180

  start:
    runs-on: ubuntu-latest

    needs: drop_db

    steps:

      - name: Checkout repository
        run: sleep 180
