name: "Deploy"

on:
  workflow_run:
    workflows: ["Build and push packages"]
    branches:
      - "master"
      - "*.*.*"
      - "develop"
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stop:
    runs-on: ubuntu-latest

    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Stop
        run: sleep 180

  drop_db:
    runs-on: ubuntu-latest

    needs: stop

    steps:
      - name: Checkout repository
        run: sleep 180

  start:
    runs-on: ubuntu-latest

    needs: drop_db

    steps:

      - name: Checkout repository
        run: sleep 180
